#include <iostream>
using namespace std;

int main(){
/*Literal
{2,3
3.14,1.2e-14
'a'
"Hello"
bool}

Var
{
/Identifier/
myNum
Illegal{
1st Num
_myText//normally generated by other program

Expression
{
1.Numerical
"+,-,/,%..."
2.Boolean
> >= < <= == !=
|| && !
}

Assignemts themselves are expressions

Conditionals 
{
if else;
if else if;
//if else is the same as if else if;
( )?_:_
switch;
}

Modifeir
{
unsiged
}

Data Type
{int, short,...
double,float...
char
string
bool
enum
}
*/

//Loop

//Methods

//cryptography = secret writing

/*
while( < bool-expr>)
{
...
}

do-while

do{
//loop body
}while(<bool expr>//contrl expr);
//do at least once iteration
//good for error check

ex.
{bool retry;
do
{
   cout << "Enter num: ";
   cin> >> countDown;
   retry = countDown<0;
   if ( retry)
      cout<<"Meh, a positive #"<<endl;
}while(retry);
}

ex2.
{int count = 3;
while((count--)>0)
   cout<<count<<" ";

count-- evaluates to 3,2,1
cout 2,1,0
}

Comma Op ,
(<expr1>, <expr2>, <expr3>)
result = (first = 1, sencond = 2);
//(result == 2) evaluates to true

for
{
for (<init expr>;<bool expr>;<update expr>)
{
   //loop body
}
*/
int n, i;

   


return 0;
}
